
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for misc configure
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+ethtool
PKG_VERSION:=1.5
PKG_RELEASE:=5

include ../luci-alias.mk

# call BuildPackage - OpenWrt buildroot signature
