#!/bin/sh /etc/rc.common

START=20

get_config() {
	config_get governor $1 governor `cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor 2>/dev/null || echo ondemand`
	config_get speed $1 speed
}

start() {
	config_load cpufreq
	config_foreach get_config cpufreq

	sh -c "echo '$governor' > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor" 2>/dev/null
	[[ "$governor" = "userspace" && -n "$speed" ]] && sh -c "echo '$speed' > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed" 2>/dev/null

	return 0
}