#!/bin/sh /etc/rc.common

START=20

get_config() {
	config_get governor $1 governor `cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor 2>/dev/null || echo ondemand`
}

start() {
	config_load cpufreq
	config_foreach get_config cpufreq

	sh -c "echo $governor > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor" 2>/dev/null

	return 0
}