#!/bin/sh /etc/rc.common

START=20

get_config() {
	config_get governor $1 governor
	config_get speed $1 speed
}

start() {
	config_load cpufreq
	config_foreach get_config cpufreq

	[[ -n "$governor" ]] || return 1

	local policy
	for policy in `ls /sys/devices/system/cpu/cpufreq/ | grep '^policy'`; do
		sh -c "echo '$governor' > /sys/devices/system/cpu/cpufreq/$policy/scaling_governor" 2>/dev/null
		[[ "$governor" = "userspace" && -n "$speed" ]] && sh -c "echo '$speed' > /sys/devices/system/cpu/cpufreq/$policy/scaling_setspeed" 2>/dev/null
	done

	return 0
}