#!/bin/sh /etc/rc.common

START=19

hwacct_config() {
	config_get hwpppoe_enabled $1 hw_pppoe "0"
}

boot() {
	local hwpppoe_enabled
	local on=on
	config_load tuning_net
	config_foreach hwacct_config hw_acct
	[ "$hwpppoe_enabled" = 0 ] && on=off

	ethtool -K eth0 hw-pppoe $on 2>/dev/null
	ethtool -K eth1 hw-pppoe $on 2>/dev/null
}

start() {
	boot
	/etc/init.d/network restart
}
