
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for UniShare
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+unishare
PKG_VERSION:=1.0.0
PKG_RELEASE:=2
PKG_MAINTAINER:=jjm2473 <jjm2473@gmail.com>

include ../luci-alias.mk

# call BuildPackage - OpenWrt buildroot signature
