#
# Copyright (C) 2022 jjm2473 <jjm2473@gmail.com>
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci for taskd
LUCI_DEPENDS:=+luci-lib-taskd

PKG_VERSION:=1.0.0
PKG_RELEASE:=
PKG_MAINTAINER:=jjm2473 <jjm2473@gmail.com>

include ../luci-alias.mk

# call BuildPackage - OpenWrt buildroot signature
