# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=MergerFS
LUCI_DEPENDS:=+luci-base +mergerfs

LUCI_PKGARCH:=all

PKG_VERSION:=1.0.2-r1
PKG_RELEASE:=
PKG_MAINTAINER:=jjm2473 <jjm2473@gmail.com>

include ../luci-alias.mk

# call BuildPackage - OpenWrt buildroot signature
